// Code generated by protoc-gen-go. DO NOT EDIT.
// source: books.proto

package GRPC

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BookRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BookRequest) Reset()         { *m = BookRequest{} }
func (m *BookRequest) String() string { return proto.CompactTextString(m) }
func (*BookRequest) ProtoMessage()    {}
func (*BookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_01e0dc127ded4184, []int{0}
}

func (m *BookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookRequest.Unmarshal(m, b)
}
func (m *BookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookRequest.Marshal(b, m, deterministic)
}
func (m *BookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookRequest.Merge(m, src)
}
func (m *BookRequest) XXX_Size() int {
	return xxx_messageInfo_BookRequest.Size(m)
}
func (m *BookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BookRequest proto.InternalMessageInfo

func (m *BookRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Book struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Isbn                 string   `protobuf:"bytes,2,opt,name=isbn,proto3" json:"isbn,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Author               *Author  `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Book) Reset()         { *m = Book{} }
func (m *Book) String() string { return proto.CompactTextString(m) }
func (*Book) ProtoMessage()    {}
func (*Book) Descriptor() ([]byte, []int) {
	return fileDescriptor_01e0dc127ded4184, []int{1}
}

func (m *Book) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Book.Unmarshal(m, b)
}
func (m *Book) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Book.Marshal(b, m, deterministic)
}
func (m *Book) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Book.Merge(m, src)
}
func (m *Book) XXX_Size() int {
	return xxx_messageInfo_Book.Size(m)
}
func (m *Book) XXX_DiscardUnknown() {
	xxx_messageInfo_Book.DiscardUnknown(m)
}

var xxx_messageInfo_Book proto.InternalMessageInfo

func (m *Book) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Book) GetIsbn() string {
	if m != nil {
		return m.Isbn
	}
	return ""
}

func (m *Book) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Book) GetAuthor() *Author {
	if m != nil {
		return m.Author
	}
	return nil
}

type Author struct {
	Firstname            string   `protobuf:"bytes,1,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Lastname             string   `protobuf:"bytes,2,opt,name=lastname,proto3" json:"lastname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Author) Reset()         { *m = Author{} }
func (m *Author) String() string { return proto.CompactTextString(m) }
func (*Author) ProtoMessage()    {}
func (*Author) Descriptor() ([]byte, []int) {
	return fileDescriptor_01e0dc127ded4184, []int{2}
}

func (m *Author) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Author.Unmarshal(m, b)
}
func (m *Author) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Author.Marshal(b, m, deterministic)
}
func (m *Author) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Author.Merge(m, src)
}
func (m *Author) XXX_Size() int {
	return xxx_messageInfo_Author.Size(m)
}
func (m *Author) XXX_DiscardUnknown() {
	xxx_messageInfo_Author.DiscardUnknown(m)
}

var xxx_messageInfo_Author proto.InternalMessageInfo

func (m *Author) GetFirstname() string {
	if m != nil {
		return m.Firstname
	}
	return ""
}

func (m *Author) GetLastname() string {
	if m != nil {
		return m.Lastname
	}
	return ""
}

type BookListResponse struct {
	Books                []*Book  `protobuf:"bytes,1,rep,name=books,proto3" json:"books,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BookListResponse) Reset()         { *m = BookListResponse{} }
func (m *BookListResponse) String() string { return proto.CompactTextString(m) }
func (*BookListResponse) ProtoMessage()    {}
func (*BookListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_01e0dc127ded4184, []int{3}
}

func (m *BookListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookListResponse.Unmarshal(m, b)
}
func (m *BookListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookListResponse.Marshal(b, m, deterministic)
}
func (m *BookListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookListResponse.Merge(m, src)
}
func (m *BookListResponse) XXX_Size() int {
	return xxx_messageInfo_BookListResponse.Size(m)
}
func (m *BookListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BookListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BookListResponse proto.InternalMessageInfo

func (m *BookListResponse) GetBooks() []*Book {
	if m != nil {
		return m.Books
	}
	return nil
}

type BookResponse struct {
	Book                 *Book    `protobuf:"bytes,1,opt,name=book,proto3" json:"book,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BookResponse) Reset()         { *m = BookResponse{} }
func (m *BookResponse) String() string { return proto.CompactTextString(m) }
func (*BookResponse) ProtoMessage()    {}
func (*BookResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_01e0dc127ded4184, []int{4}
}

func (m *BookResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookResponse.Unmarshal(m, b)
}
func (m *BookResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookResponse.Marshal(b, m, deterministic)
}
func (m *BookResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookResponse.Merge(m, src)
}
func (m *BookResponse) XXX_Size() int {
	return xxx_messageInfo_BookResponse.Size(m)
}
func (m *BookResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BookResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BookResponse proto.InternalMessageInfo

func (m *BookResponse) GetBook() *Book {
	if m != nil {
		return m.Book
	}
	return nil
}

type NoRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NoRequest) Reset()         { *m = NoRequest{} }
func (m *NoRequest) String() string { return proto.CompactTextString(m) }
func (*NoRequest) ProtoMessage()    {}
func (*NoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_01e0dc127ded4184, []int{5}
}

func (m *NoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NoRequest.Unmarshal(m, b)
}
func (m *NoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NoRequest.Marshal(b, m, deterministic)
}
func (m *NoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NoRequest.Merge(m, src)
}
func (m *NoRequest) XXX_Size() int {
	return xxx_messageInfo_NoRequest.Size(m)
}
func (m *NoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NoRequest proto.InternalMessageInfo

func init() {
	proto.RegisterType((*BookRequest)(nil), "proto.BookRequest")
	proto.RegisterType((*Book)(nil), "proto.Book")
	proto.RegisterType((*Author)(nil), "proto.Author")
	proto.RegisterType((*BookListResponse)(nil), "proto.BookListResponse")
	proto.RegisterType((*BookResponse)(nil), "proto.BookResponse")
	proto.RegisterType((*NoRequest)(nil), "proto.NoRequest")
}

func init() {
	proto.RegisterFile("books.proto", fileDescriptor_01e0dc127ded4184)
}

var fileDescriptor_01e0dc127ded4184 = []byte{
	// 322 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x90, 0xcf, 0x4a, 0xf3, 0x40,
	0x14, 0xc5, 0x49, 0x9a, 0xf4, 0xcf, 0x9d, 0xef, 0x93, 0x72, 0x15, 0x0c, 0x45, 0xb1, 0x0e, 0x08,
	0x5d, 0xb5, 0x10, 0xe9, 0xa2, 0x4b, 0xeb, 0xc2, 0x8d, 0x88, 0xc4, 0x9d, 0xbb, 0xb4, 0xb9, 0xd6,
	0xa1, 0x35, 0x13, 0x33, 0x13, 0x1f, 0xc7, 0x67, 0x95, 0xcc, 0x8c, 0x35, 0x2d, 0x75, 0xe3, 0x2a,
	0x99, 0x73, 0xee, 0x6f, 0xce, 0x99, 0x0b, 0x6c, 0x21, 0xe5, 0x5a, 0x8d, 0x8b, 0x52, 0x6a, 0x89,
	0xa1, 0xf9, 0xf0, 0x73, 0x60, 0x73, 0x29, 0xd7, 0x09, 0xbd, 0x57, 0xa4, 0x34, 0x1e, 0x81, 0x2f,
	0xb2, 0xc8, 0x1b, 0x7a, 0xa3, 0x5e, 0xe2, 0x8b, 0x8c, 0xaf, 0x20, 0xa8, 0xed, 0x7d, 0x1d, 0x11,
	0x02, 0xa1, 0x16, 0x79, 0xe4, 0x1b, 0xc5, 0xfc, 0xe3, 0x09, 0x84, 0x5a, 0xe8, 0x0d, 0x45, 0x2d,
	0x23, 0xda, 0x03, 0x5e, 0x41, 0x3b, 0xad, 0xf4, 0xab, 0x2c, 0xa3, 0x60, 0xe8, 0x8d, 0x58, 0xfc,
	0xdf, 0xe6, 0x8f, 0x6f, 0x8c, 0x98, 0x38, 0x93, 0xcf, 0xa1, 0x6d, 0x15, 0x3c, 0x83, 0xde, 0x8b,
	0x28, 0x95, 0xce, 0xd3, 0x37, 0x72, 0x89, 0x3f, 0x02, 0x0e, 0xa0, 0xbb, 0x49, 0x9d, 0x69, 0xc3,
	0xb7, 0x67, 0x3e, 0x85, 0x7e, 0x5d, 0xf6, 0x5e, 0x28, 0x9d, 0x90, 0x2a, 0x64, 0xae, 0x08, 0x2f,
	0x21, 0x34, 0xaf, 0x8e, 0xbc, 0x61, 0x6b, 0xc4, 0x62, 0xe6, 0xd2, 0xcd, 0x9b, 0xad, 0xc3, 0x27,
	0xf0, 0xcf, 0xae, 0xc0, 0x21, 0x17, 0x10, 0xd4, 0x86, 0xc9, 0xde, 0x23, 0x8c, 0xc1, 0x19, 0xf4,
	0x1e, 0xa4, 0xdb, 0x58, 0xfc, 0xe9, 0xdb, 0x0d, 0x3e, 0x51, 0xf9, 0x21, 0x96, 0x84, 0x53, 0xe8,
	0xae, 0x48, 0xd7, 0x8a, 0xc2, 0xbe, 0x63, 0xb7, 0xd3, 0x83, 0xd3, 0xc6, 0x6d, 0x3b, 0x3d, 0x63,
	0xe8, 0x38, 0x0c, 0xb1, 0x99, 0xe8, 0xb8, 0xe3, 0x1d, 0xcd, 0x31, 0x63, 0x80, 0x65, 0x49, 0xa9,
	0x26, 0x83, 0x35, 0x8b, 0x1e, 0x9e, 0x9f, 0x01, 0x54, 0x45, 0xf6, 0x3d, 0x7f, 0x28, 0xe6, 0xd7,
	0x7a, 0x33, 0x80, 0x8c, 0x36, 0xf4, 0x07, 0x74, 0xde, 0x79, 0x0e, 0x27, 0x77, 0xc9, 0xe3, 0xed,
	0xa2, 0x6d, 0x06, 0xae, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0x8e, 0xb2, 0x3c, 0x0a, 0x87, 0x02,
	0x00, 0x00,
}
